---
title: "Tips"
weight: 2
---

** Org
   :PROPERTIES:
   :CUSTOM_ID: org
   :END:

Use [[https://emacs.stackexchange.com/questions/51755/org-mode-link-files-with-ids-and-not-filenames][org-id]] for global link UUIDs that are not path-dependent. Otherwise links will be fragile and temporary.

To summarize the above link: Customize org-id-link-to-org-use-id to create-if-interactive.

I also needed to add this line in my Spacemacs config:

#+begin_src elisp
(with-eval-after-load 'org
;; Use global IDs (for unique links)
(require 'org-id))
#+end_src

** Dired
   :PROPERTIES:
   :CUSTOM_ID: dired
   :END:

Configure Dired to sort directories before files. You can edit Dired ls
switches with dired-sort-toggle-or-edit.

Where possible, capitalize files and directories. This makes it easy to
target them with isearch in minimal keystrokes. Omit superfluous
extensions to reduce visual clutter with dired-omit-mode.

** Spacemacs
   :PROPERTIES:
   :CUSTOM_ID: spacemacs
   :END:

Spacemacs is the best way for beginners to learn Emacs, as it provides
powerful user-friendly customizations. Start in Holy mode with Helm.

** Inductive sorting
   :PROPERTIES:
   :CUSTOM_ID: inductive-sorting
   :END:

Treefactor sorting is fast. Think with your fingers, not your brain. You
can always redo it later. It is often better to do it wrong and learn
something than to sit there just thinking about it. Handling the
material improves your feel of the subject. Pretend you're a raccoon
rubbing the muck off a squirmy snack pulled from the stream.

{{< youtube 4FGGn1YTBWc >}}
